---
build:
  version: v1.0.0  # version of the build is informative

# list of versions
versions:
  -
    tag:  "v0.0.0-dev"
    solc: '0.8.13'
    solidity_file: "src/commerce/Payment.sol"
    use: "272558e8f753529315896ab2ffa7f1eda3fd7ee7"
    output_folder: "commerce"
    dependencies: "openzeppelin/=lib/openzeppelin-contracts/"
  -
    tag: "v0.0.0-dev"
    solc: '0.8.13'
    solidity_file: "src/commerce/ElvTokenUpgradeable.sol"
    use: "6092476a88afcaf3f06211d0fd9bbe43a9a8561d"
    output_folder: "elv_token_upgradeable"
    dependencies: "openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
  -
    tag: "v0.0.0-dev"
    solc: '0.8.13'
    solidity_file: "lib/openzeppelin-contracts/contracts/proxy/ERC1967/ERC1967Proxy.sol"
    use: "6092476a88afcaf3f06211d0fd9bbe43a9a8561d"
    output_folder: "proxy"
    dependencies: "openzeppelin/=lib/openzeppelin-contracts/"
