---
build:
  version: v1.0.0  # version of the build is informative

# list of versions
versions:
  -
    tag:  "v0.0.0-dev"
    solc: '0.8.13'
    solidity_file: "src/commerce/Payment.sol"
    use: "272558e8f753529315896ab2ffa7f1eda3fd7ee7"
    output_folder: "commerce"
    dependencies: "openzeppelin/=lib/openzeppelin-contracts/"
  -
    tag: "v0.0.0-dev"
    solc: '0.8.13'
    solidity_file: "src/commerce/ElvToken.sol"
    use: "272558e8f753529315896ab2ffa7f1eda3fd7ee7"
    output_folder: "elv_token"
    dependencies: "openzeppelin/=lib/openzeppelin-contracts/"
