---
build:
  version: v1.0.0  # version of the build is informative

# list of versions
versions:
  -
    tag:  "v0.0.1"
    solc: '0.8.13'
    solidity_file: "src/commerce/Payment.sol"
    use: "591bce9bce2ae22a4498100d046a07805f63a277"
    output_folder: "commerce"
    dependencies: "openzeppelin/=lib/openzeppelin-contracts/"
  -
    tag: "v0.0.1"
    solc: '0.8.13'
    solidity_file: "src/commerce/ElvTokenPermit.sol"
    use: "591bce9bce2ae22a4498100d046a07805f63a277"
    output_folder: "token_permit"
    dependencies: "openzeppelin/=lib/openzeppelin-contracts/"
